name = "Reflexicons"
uuid = "644c6a88-f588-41ff-bb6a-8a2790f1d811"
authors = ["Jake Ireland <jakewilliami@icloud.com> and contributors"]
version = "0.1.2"

[deps]
SpelledOut = "4728c690-e668-4265-bc0d-51a8c0f93067"

[compat]
SpelledOut = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
